on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  build:
    strategy:
      matrix:
        arch: [x86_64, aarch64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build server
        run: |
          make docker ARCHS=${{ matrix.arch }}
      - name: Upload server
        uses: actions/upload-artifact@v4
        with:
          name: server-${{ matrix.arch }}
          path: output/built/OpenAppleMacrosServer-${{ matrix.arch }}
  create-release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download servers
        uses: actions/download-artifact@v4
        with:
          pattern: server-*
          path: servers
      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          tag="${{ github.ref_name }}"
          gh release create "$tag" --draft --title "$tag"
          gh release upload "$tag" servers/**/OpenAppleMacrosServer-*
