on:
  push:
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build
        run: make docker -j2
      - name: Create release
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          gh release create "${{ github.sha }}" --draft --title "Draft Release"
          gh release upload "${{ github.sha }}" output/*/built/OpenAppleMacrosServer-*
